---
title: "Sampler"
author: "Jim Ianelli"
date: "August 21th, 2015"
#output: 
output: binb::metropolis
fontsize: 12pt
 #flexdashboard::flex_dashboard:
    #orientation: columns
    #vertical_layout: fill
---

------------------------------------------------------------------------

# Introduction

This document provides some example sets of functions useful for compiling data from updated observer program information 

This was developed originally by Kimura (1989) with a modification Dorn and Kimura (1992?).
In converting the original FORTRAN code we added bootstrap facilities to obtain variance estimates.

**Kimura 1989:**   *"Formulas are derived for estimating catch-in-numbers-at age for complex, multi-area, multi-nation, multi-gear fisheries. Assuming catch-in-weight is known for each substratum, the method involves applying randomly sampled length frequencies from these substrata to age-length and weight-length keys sampled from broader strata. Variance estimates are derived using standard statistical calculations and the delta method. This variance is the variance due to the biological sampling of age, length, and weight. "*

# Equations

```         
Sampler()
```
# Within strata sampling

```{mermaid}
graph TD;
    Hauls{Hauls} --> Lengths{Lengths}
    Hauls --> Ages{Ages}
    Ages --> ALK
    Lengths --> Catch_at_length
    Catch_at_length--> Catch_at_Age
    ALK --> Catch_at_Age
  %%loop Apply
    %%Catch_at_length->>Catch_at_length: sum shit
   %%end
    
```
```{mermaid}
sequenceDiagram
  participant Alice
  participant Bob
  Alice->>John: Hello John, how are you?
  loop Healthcheck
    John->>John: Fight against hypochondria
  end
```

# Functions

term

:   w_a=weight (body mass) at age

$w_a = \frac{w_{a-1} + w_a}{2}$


# Functions

```         
Sampler()
```
